<a href="https://colab.research.google.com/github/Ramsi-git/Assignment-on-NumPy-Pandas/blob/main/Assignment_on_Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Q1. Employee Salary Adjustment

In [ ]:
#import numpy
import numpy as np
#A company stores salaries in a Numpy array.
salaries = np.array([45000, 52000, 61000, 48000, 75000])

In [ ]:
#Increase all salaries by 10%.
increased_salaries=salaries*1.10
print(increased_salaries)

[49500. 57200. 67100. 52800. 82500.]


In [ ]:
#Find the average salary.
avg_salary=np.mean(increased_salaries)
print(avg_salary)

61820.0


In [ ]:
#Find the maximum and minimum salary.
max_sal=np.max(increased_salaries)
min_sal=np.min(increased_salaries)
print(max_sal)
print(min_sal)

82500.0
49500.00000000001


In [ ]:
#Print salaries greater than 60000.
above_60k=increased_salaries[increased_salaries>60000]
print(above_60k)

[67100. 82500.]


#Q2. Sales Data Analysis

In [ ]:
#Daily sales of a store for 10 days:
sales = np.array([120,150,180,200,170,160,210,220,190,175])

In [ ]:
#Compute total sales.
total_sales = np.sum(sales)
print(total_sales)

1775


In [ ]:
#Compute mean and standard deviation.
mean_sales = np.mean(sales)
std_sales = np.std(sales)
print(mean_sales)
print(std_sales)

177.5
28.217902119044926


In [ ]:
#Identify days where sales exceeded the average.
high_sales_days = sales[sales > mean_sales]
print(high_sales_days)

[180 200 210 220 190]


In [ ]:
#Normalize the sales using Min-Max scaling.
norm_sales = (sales - np.min(sales)) / (np.max(sales) - np.min(sales))
print(f"Normalized Sales: {norm_sales}")

Normalized Sales: [0.   0.3  0.6  0.8  0.5  0.4  0.9  1.   0.7  0.55]


#Q3. Matrix Operations for Business Data

In [ ]:
#A company has sales data for 3 products across 4 regions.
sales_matrix = np.array([[120,140,130,150], [80,90,100,95], [200,210,190,205]])

In [ ]:
#Find total sales per product.
prod_totals = np.sum(sales_matrix, axis=1)
print(prod_totals)

[540 365 805]


In [ ]:
#Find total sales per region.
region_totals = np.sum(sales_matrix, axis=0)
print(region_totals)

[400 440 420 450]


In [ ]:
#Identify the best performing product.
best_prod_idx = np.argmax(prod_totals) + 1
print(best_prod_idx)

3


In [ ]:
#Identify the region with highest sales.
best_region_idx = np.argmax(region_totals) + 1
print(best_region_idx)

4


#Q4. Employee Dataset Exploration

In [ ]:
#import pandas
import pandas as pd
#Create a DataFrame:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4]
}

In [ ]:
#Convert this dictionary into a DataFrame.
df = pd.DataFrame(data)
print(df)

  Employee Department  Salary  Experience
0        A         HR   50000           2
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6
4        E         HR   52000           3
5        F    Finance   68000           4


In [ ]:
#Display basic statistics of the dataset.
stats = df.describe()
print(stats)

             Salary  Experience
count      6.000000    6.000000
mean   62833.333333    4.500000
std     9474.527253    1.870829
min    50000.000000    2.000000
25%    55250.000000    3.250000
50%    66500.000000    4.500000
75%    69500.000000    5.750000
max    72000.000000    7.000000


In [ ]:
#Find the average salary per department.
dept_avg = df.groupby('Department')['Salary'].mean()
print(dept_avg)

Department
Finance    70000.0
HR         51000.0
IT         67500.0
Name: Salary, dtype: float64


In [ ]:
#Identify employees with experience greater than 4 years.
senior_emp = df[df['Experience'] > 4]
print(senior_emp)

  Employee Department  Salary  Experience
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6


In [ ]:
#Add a new column Bonus = 10% of salary.
df['Bonus'] = df['Salary'] * 0.10
print(df)

  Employee Department  Salary  Experience   Bonus
0        A         HR   50000           2  5000.0
1        B         IT   65000           5  6500.0
2        C         IT   70000           7  7000.0
3        D    Finance   72000           6  7200.0
4        E         HR   52000           3  5200.0
5        F    Finance   68000           4  6800.0


#Q5. Missing Data Handling

In [ ]:
#Dataset:
data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000]
}
df_missing = pd.DataFrame(data)
print(df_missing)

    Name   Age   Salary
0   John  28.0  50000.0
1   Anna   NaN  54000.0
2  Peter  35.0      NaN
3  Linda  32.0  58000.0
4  David   NaN  60000.0


In [ ]:
#Detect missing values.
print(df_missing.isnull().sum())

Name      0
Age       2
Salary    1
dtype: int64


In [ ]:
#Replace missing Age with mean age.
df_missing['Age'] = df_missing['Age'].fillna(df_missing['Age'].mean())
print(df_missing)

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000      NaN
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0


In [ ]:
#Replace missing Salary with median salary.
df_missing['Salary'] = df_missing['Salary'].fillna(df_missing['Salary'].median())
print(df_missing)

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0


In [ ]:
#Remove rows with any remaining missing values.
df_cleaned = df_missing.dropna()
print(df_cleaned)

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0


#Q6. Sales Performance Analysis

In [ ]:
#Dataset:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}
df_sales = pd.DataFrame(sales_data)
print(df_sales)

  Region Salesperson  Sales
0  North           A  12000
1  South           B  15000
2   East           C  13000
3   West           D  17000
4  North           E  16000
5  South           F  14000
6   East           G  15500
7   West           H  16500


In [ ]:
#Find total sales per region.
region_sales = df_sales.groupby('Region')['Sales'].sum()
print(region_sales)

Region
East     28500
North    28000
South    29000
West     33500
Name: Sales, dtype: int64


In [ ]:
#Identify the top salesperson.
top_person = df_sales.loc[df_sales['Sales'].idxmax()]
print(top_person)

Region          West
Salesperson        D
Sales          17000
Name: 3, dtype: object


In [ ]:
#Compute average sales across regions.
avg_reg_sales = df_sales.groupby('Region')['Sales'].mean()
print(avg_reg_sales)

Region
East     14250.0
North    14000.0
South    14500.0
West     16750.0
Name: Sales, dtype: float64


In [ ]:
#Sort the dataset by sales descending.
df_sorted = df_sales.sort_values(by='Sales', ascending=False)
print(df_sorted)

  Region Salesperson  Sales
3   West           D  17000
7   West           H  16500
4  North           E  16000
6   East           G  15500
1  South           B  15000
5  South           F  14000
2   East           C  13000
0  North           A  12000


#Q7. Customer Purchase Analysis

In [ ]:
#Dataset:
data_cust= {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}
df_cust = pd.DataFrame(data_cust)
print(df_cust)

   CustomerID  Age  PurchaseAmount     City
0         101   25             250    Delhi
1         102   45             600   Mumbai
2         103   35             400    Delhi
3         104   50             800  Chennai
4         105   23             150   Mumbai
5         106   40             700    Delhi
6         107   60             900  Chennai


In [ ]:
#Find the average purchase amount by city
city_avg = df_cust.groupby('City')['PurchaseAmount'].mean()
print(city_avg)

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: PurchaseAmount, dtype: float64


In [ ]:
# Identify customers with purchase above overall average.
high_buyers = df_cust[df_cust['PurchaseAmount'] > df_cust['PurchaseAmount'].mean()]
print(high_buyers)

   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai


In [ ]:
#Find the city generating the highest revenue.
top_city = df_cust.groupby('City')['PurchaseAmount'].sum().idxmax()
print("Top City:" ,top_city)

Top City: Chennai


In [ ]:
#Create a column Age_Group:
# <30 → Young
# 30–50 → Adult
# 50 → Senior
def age_cat(age):
    if age < 30: return 'Young'
    elif 30 <= age <= 50: return 'Adult'
    else: return 'Senior'

df_cust['Age_Group'] = df_cust['Age'].apply(age_cat)
print(df_cust)

   CustomerID  Age  PurchaseAmount     City Age_Group
0         101   25             250    Delhi     Young
1         102   45             600   Mumbai     Adult
2         103   35             400    Delhi     Adult
3         104   50             800  Chennai     Adult
4         105   23             150   Mumbai     Young
5         106   40             700    Delhi     Adult
6         107   60             900  Chennai    Senior


In [ ]:
#Find average purchase per age group.
age_group_avg = df_cust.groupby('Age_Group')['PurchaseAmount'].mean()
print(age_group_avg)

Age_Group
Adult     625.0
Senior    900.0
Young     200.0
Name: PurchaseAmount, dtype: float64


#Q8: Time Series Sales Analysis

In [ ]:
#Generate data:
dates = pd.date_range('2024-01-01', periods=12, freq='ME') # 'ME' for Month End
sales_ts = [200, 220, 250, 270, 300, 320, 350, 360, 380, 400, 420, 450]
df_ts = pd.DataFrame({'Date': dates, 'Sales': sales_ts})
print(df_ts)

         Date  Sales
0  2024-01-31    200
1  2024-02-29    220
2  2024-03-31    250
3  2024-04-30    270
4  2024-05-31    300
5  2024-06-30    320
6  2024-07-31    350
7  2024-08-31    360
8  2024-09-30    380
9  2024-10-31    400
10 2024-11-30    420
11 2024-12-31    450


In [ ]:
#Convert Date to datetime index.
df_ts.set_index('Date', inplace=True)
print(df_ts.index)

DatetimeIndex(['2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31',
               '2024-09-30', '2024-10-31', '2024-11-30', '2024-12-31'],
              dtype='datetime64[ns]', name='Date', freq=None)


In [ ]:
#Compute monthly percentage growth.
df_ts['Growth'] = df_ts['Sales'].pct_change() * 100
print(df_ts[['Sales','Growth']])

            Sales     Growth
Date                        
2024-01-31    200        NaN
2024-02-29    220  10.000000
2024-03-31    250  13.636364
2024-04-30    270   8.000000
2024-05-31    300  11.111111
2024-06-30    320   6.666667
2024-07-31    350   9.375000
2024-08-31    360   2.857143
2024-09-30    380   5.555556
2024-10-31    400   5.263158
2024-11-30    420   5.000000
2024-12-31    450   7.142857


In [ ]:
#Calculate 3-month rolling average sales.
df_ts['Rolling_Avg'] = df_ts['Sales'].rolling(window=3).mean()
print(df_ts[['Sales','Rolling_Avg']])

            Sales  Rolling_Avg
Date                          
2024-01-31    200          NaN
2024-02-29    220          NaN
2024-03-31    250   223.333333
2024-04-30    270   246.666667
2024-05-31    300   273.333333
2024-06-30    320   296.666667
2024-07-31    350   323.333333
2024-08-31    360   343.333333
2024-09-30    380   363.333333
2024-10-31    400   380.000000
2024-11-30    420   400.000000
2024-12-31    450   423.333333


In [ ]:
#Identify the month with highest growth rate.
highest_growth_month = df_ts['Growth'].idxmax()
print(df_ts)
print(f"Highest Growth Month: {highest_growth_month}")

            Sales     Growth  Rolling_Avg
Date                                     
2024-01-31    200        NaN          NaN
2024-02-29    220  10.000000          NaN
2024-03-31    250  13.636364   223.333333
2024-04-30    270   8.000000   246.666667
2024-05-31    300  11.111111   273.333333
2024-06-30    320   6.666667   296.666667
2024-07-31    350   9.375000   323.333333
2024-08-31    360   2.857143   343.333333
2024-09-30    380   5.555556   363.333333
2024-10-31    400   5.263158   380.000000
2024-11-30    420   5.000000   400.000000
2024-12-31    450   7.142857   423.333333
Highest Growth Month: 2024-03-31 00:00:00
